/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dersane;


import dersane.Connection.Faturalar;
import dersane.Connection.Islemler;
import dersane.Connection.OracleDbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukriye
 */
public class OgrenciDersSecim extends javax.swing.JFrame {
    private  Connection conn =null;
    private Statement stmt = null;
    private PreparedStatement pstmt,pstmt2 =null;
    private int toplam_tutar=0;
    Faturalar yeni = new Faturalar();
   
    /**
     * Creates new form OgrenciDersSecim
     */
    
    public OgrenciDersSecim() {
        initComponents();
        try {
            Class.forName(OracleDbConnection.driverName);
            try {
            conn =DriverManager.getConnection(OracleDbConnection.URL,OracleDbConnection.userName,OracleDbConnection.password);
            stmt=conn.createStatement();
        } 
            catch (SQLException ex) {
                 System.out.println("Bağlantı Başarısız ");
                 System.out.println(ex);
            }
        } 
        catch (ClassNotFoundException ex) {
          System.out.println("Driver Bulunamadı ");
          System.out.println(ex);
        }
        
        try {
            ResultSet rs =stmt.executeQuery("SELECT DERS_KODU FROM DERS");
            while(rs.next()){
               ders_1.addItem(rs.getString("DERS_KODU"));
               ders_2.addItem(rs.getString("DERS_KODU"));
               ders_3.addItem(rs.getString("DERS_KODU"));
               ders_4.addItem(rs.getString("DERS_KODU"));
               ders_5.addItem(rs.getString("DERS_KODU"));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ogrenci.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tc_alani = new javax.swing.JTextField();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fatura_Tutar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tak_say = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hesapla = new javax.swing.JButton();
        ders_1 = new javax.swing.JComboBox();
        ders_2 = new javax.swing.JComboBox();
        ders_3 = new javax.swing.JComboBox();
        ders_4 = new javax.swing.JComboBox();
        ders_5 = new javax.swing.JComboBox();
        kaydet = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(242, 255, 232));

        guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-update-64.png"))); // NOI18N
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-delete-bin-64.png"))); // NOI18N
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        jLabel12.setText("Öğrenci T.C No:");

        jLabel1.setText("Ders Adı:");

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-back-arrow-64.png"))); // NOI18N
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        jLabel2.setText("Ders Adı:");

        jLabel13.setText("Toplam Fatura Tutarı :");

        jLabel4.setText("Ders Adı:");

        jLabel14.setText("Taksit Sayısı :");

        jLabel5.setText("Ders Adı:");

        fatura_Tutar.setEditable(false);

        jLabel6.setText("Ders Adı:");

        tak_say.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel7.setText("Ders Ücreti");

        jLabel8.setText("Ders Ücreti");

        jLabel9.setText("Ders Ücreti");

        jLabel10.setText("Ders Ücreti");

        jLabel11.setText("Ders Ücreti");

        hesapla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-calculator-96.png"))); // NOI18N
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        ders_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz" }));
        ders_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ders_1ActionPerformed(evt);
            }
        });

        ders_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz" }));

        ders_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz" }));
        ders_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ders_3ActionPerformed(evt);
            }
        });

        ders_4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz" }));

        ders_5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz" }));

        kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-save-close-64.png"))); // NOI18N
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-book-shelf-96.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-search-property-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tc_alani)
                            .addComponent(ders_1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ders_2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ders_3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ders_4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ders_5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fatura_Tutar)
                                    .addComponent(tak_say, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ders_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ders_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(ders_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ders_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ders_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(fatura_Tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tak_say, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sil)
                        .addComponent(kaydet)
                        .addComponent(guncelle))
                    .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addGap(353, 353, 353))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed
        // TODO add your handling code here:
        String ders1= (String) ders_1.getSelectedItem();
        String ders2= (String) ders_2.getSelectedItem();
        String ders3= (String) ders_3.getSelectedItem();
        String ders4= (String) ders_4.getSelectedItem();
        String ders5= (String) ders_5.getSelectedItem();
        int ucret1 = 0,ucret2=0,ucret3=0,ucret4=0,ucret5=0;
        
        String sorgu ="SELECT * FROM DERS WHERE DERS_KODU =?";
        if(ders1 == "Seçiniz"){
            ucret1=0;
            jLabel7.setText("0");
        }
        else {
            ResultSet rs;
            try {
                pstmt=conn.prepareStatement(sorgu);
            //stmt =conn.createStatement();
            pstmt.setString(1, ders1);
                rs = pstmt.executeQuery();
                while(rs.next()){
                ucret1= (rs.getInt("UCRET"));
                jLabel7.setText(rs.getString("UCRET"));
            }
            } catch (SQLException ex) {
                Logger.getLogger(OgrenciDersSecim.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        if(ders2 == "Seçiniz"){
            ucret2=0;
            jLabel8.setText("0");
        }
        else {
            ResultSet rs;
            try {
                pstmt=conn.prepareStatement(sorgu);
            //stmt =conn.createStatement();
            pstmt.setString(1, ders2);
                rs = pstmt.executeQuery();
                while(rs.next()){
                ucret2= (rs.getInt("UCRET"));
                jLabel8.setText(rs.getString("UCRET"));
            }
            } catch (SQLException ex) {
                Logger.getLogger(OgrenciDersSecim.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        if(ders3 == "Seçiniz"){
            ucret3=0;
            jLabel9.setText("0");
        }
        else {
            ResultSet rs;
            try {
                pstmt=conn.prepareStatement(sorgu);
            //stmt =conn.createStatement();
            pstmt.setString(1, ders3);
                rs = pstmt.executeQuery();
                while(rs.next()){
                ucret3= (rs.getInt("UCRET"));
                jLabel9.setText(rs.getString("UCRET"));
            }
            } catch (SQLException ex) {
                Logger.getLogger(OgrenciDersSecim.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        if(ders4 == "Seçiniz"){
            ucret4=0;
            jLabel10.setText("0");
        }
        else {
            ResultSet rs;
            try {
                pstmt=conn.prepareStatement(sorgu);
            //stmt =conn.createStatement();
            pstmt.setString(1, ders4);
                rs = pstmt.executeQuery();
                while(rs.next()){
                ucret4= (rs.getInt("UCRET"));
                jLabel10.setText(rs.getString("UCRET"));
            }
            } catch (SQLException ex) {
                Logger.getLogger(OgrenciDersSecim.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        if(ders5 == "Seçiniz"){
            ucret5=0;
            jLabel11.setText("0");
        }
        else {
            ResultSet rs;
            try {
                pstmt=conn.prepareStatement(sorgu);
            //stmt =conn.createStatement();
            pstmt.setString(1, ders5);
                rs = pstmt.executeQuery();
                while(rs.next()){
                ucret5= (rs.getInt("UCRET"));
                jLabel11.setText(rs.getString("UCRET"));
            }
            } catch (SQLException ex) {
                Logger.getLogger(OgrenciDersSecim.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        toplam_tutar=ucret1+ucret2+ucret3+ucret4+ucret5;
        fatura_Tutar.setText(String.valueOf(toplam_tutar));
        tutardon(toplam_tutar);
        
    }//GEN-LAST:event_hesaplaActionPerformed

    public int tutardon(int tutar){
        System.out.println("tutar " +tutar);
        return tutar;
    }
    private void ders_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ders_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ders_3ActionPerformed

    private void ders_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ders_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ders_1ActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        // TODO add your handling code here:
        String ders1= (String) ders_1.getSelectedItem();
        String ders2= (String) ders_2.getSelectedItem();
        String ders3= (String) ders_3.getSelectedItem();
        String ders4= (String) ders_4.getSelectedItem();
        String ders5= (String) ders_5.getSelectedItem();
        String taksit= (String) tak_say.getSelectedItem();
        
        String ogrtc=tc_alani.getText();
        String sorgu ="INSERT INTO OGRENCI_DERS(OGRENCI_TC,ILK_DERS,IKINCI_DERS,UCUNCU_DERS,DORDUNCU_DERS,BESINCI_DERS)" + "VALUES (?,?,?,?,?,?)";
        String sorgu2 ="INSERT INTO FATURA (TAKSIT_SAYISI,TOPLAM_TUTAR,OGRENCI_TC)"+ "VALUES (?,?,?)";  
        try {
            pstmt2=conn.prepareStatement(sorgu2);
            pstmt2.setString(1, taksit);
            pstmt2.setString(2, String.valueOf(toplam_tutar));
            pstmt2.setString(3, ogrtc);
            
            pstmt2.executeUpdate();
            JOptionPane.showMessageDialog(null,"Başarıyla Eklendi." ); 
            yeni.setTutar(toplam_tutar);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VeliBilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pstmt=conn.prepareStatement(sorgu);
            pstmt.setString(1, ogrtc);
            pstmt.setString(2, ders1);
            pstmt.setString(3, ders2);
            pstmt.setString(4, ders3);
            pstmt.setString(5, ders4);
            pstmt.setString(6, ders5);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Başarıyla Eklendi." ); 
            yeni.setTutar(toplam_tutar);
            
        
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VeliBilgi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_kaydetActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        // TODO add your handling code here:
        String tc= tc_alani.getText();
        if (tc.length()==11){
            String sorgu = "DELETE FROM OGRENCI WHERE TC_NO = ?";
        
        try {
            pstmt=conn.prepareStatement(sorgu);
           
            pstmt.setString(1, tc);
            
           pstmt.executeQuery();
            
            JOptionPane.showMessageDialog(null, "Kayıt Silindi. ");
            tc_alani.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(OgrenciDersSecim.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Kayıt Silinemedi. " );
            
        }
           
       }
       else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
       }
    }//GEN-LAST:event_silActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        // TODO add your handling code here:
        String ders1= (String) ders_1.getSelectedItem();
        String ders2= (String) ders_2.getSelectedItem();
        String ders3= (String) ders_3.getSelectedItem();
        String ders4= (String) ders_4.getSelectedItem();
        String ders5= (String) ders_5.getSelectedItem();
        String ogrtc=tc_alani.getText();
        if (ogrtc.length()==11){
           //islemler.ogrenci_Guncelle(sube,tc,ad,soyad,telefon,cinsiyet,adres);
            String sorgu = "UPDATE  OGRENCI  SET OGRENCI_TC = ? , ILK_DERS = ? ,IKINCI_DERS = ? , UCUNU_DERS = ? , DORDUNCU_DERS = ? , BESINCI_DERS =?  WHERE OGRENCI_TC = ?";
        
        try {
            pstmt=conn.prepareStatement(sorgu);
            pstmt.setString(1, ogrtc);
            pstmt.setString(2, ders1);
            pstmt.setString(3, ders2);
            pstmt.setString(4, ders3);
            pstmt.setString(5, ders4);
            pstmt.setString(6, ders5);
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Kayıt Güncellendi. ");
           
            tc_alani.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(OgrenciDersSecim.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Kayıt Güncellenemedi. ");
             
            
        }
           
       }
       else if (ogrtc.length()>11 || ogrtc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
       }
        
    }//GEN-LAST:event_guncelleActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        // TODO add your handling code here:
        Menu form = new Menu();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OgrenciDersSecim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ders_1;
    private javax.swing.JComboBox ders_2;
    private javax.swing.JComboBox ders_3;
    private javax.swing.JComboBox ders_4;
    private javax.swing.JComboBox ders_5;
    private javax.swing.JTextField fatura_Tutar;
    private javax.swing.JButton geri;
    private javax.swing.JButton guncelle;
    private javax.swing.JButton hesapla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kaydet;
    private javax.swing.JButton sil;
    private javax.swing.JComboBox tak_say;
    private javax.swing.JTextField tc_alani;
    // End of variables declaration//GEN-END:variables
}
