/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dersane;

import dersane.Connection.Islemler;
import dersane.Connection.OracleDbConnection;
import dersane.Connection.Personeller;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sukriye
 */
public class Personel extends javax.swing.JFrame {
     public DefaultListModel dm=new DefaultListModel();
private  Connection conn =null;
    private Statement stmt = null;
    private PreparedStatement pstmt =null;
    DefaultTableModel model;
    
    /**
     * Creates new form NewJFrame
     */
    public Personel() {
        initComponents();
        model = (DefaultTableModel) tablo.getModel();
        
        
        try {
            Class.forName(OracleDbConnection.driverName);
            try {
            conn =DriverManager.getConnection(OracleDbConnection.URL,OracleDbConnection.userName,OracleDbConnection.password);
            stmt=conn.createStatement();
        } 
            catch (SQLException ex) {
                 System.out.println("Bağlantı Başarısız ");
                 System.out.println(ex);
            }
        } 
        catch (ClassNotFoundException ex) {
          System.out.println("Driver Bulunamadı ");
          System.out.println(ex);
        }
        
        try {
            ResultSet rs =stmt.executeQuery("SELECT SUBE_ID FROM SUBE");
            while(rs.next()){
               sube.addItem(rs.getString("SUBE_ID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ogrenci.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultSet rs =stmt.executeQuery("SELECT MESLEK_ID FROM MESLEK");
            while(rs.next()){
               meslek_db.addItem(rs.getString("MESLEK_ID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ogrenci.class.getName()).log(Level.SEVERE, null, ex);
        }
        doldur();
    }
    
    public void doldur(){
        try {
            ResultSet rs= stmt.executeQuery("SELECT * FROM PERSONEL");
            int a= rs.getMetaData().getColumnCount();
            DefaultTableModel table= new DefaultTableModel();
            for (int i=1; i<=a; i++)
                table.addColumn(rs.getMetaData().getColumnName(i));

            while(rs.next()){
                    Object[] row =new Object[a];
                    for(int x=1; x<=a;x++){
                        row[x-1]=rs.getObject(x);
                        
                    }
                    table.addRow(row);
                    //System.out.println("ne yapıyorsun sen acaba");
                        
                    tablo.setModel(table);
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Ogrenci.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        soyad_alani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        med_hal = new javax.swing.JComboBox();
        adres_alani = new javax.swing.JTextField();
        maas_alani = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        ekle = new javax.swing.JButton();
        sube = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        ara = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        ad_alani = new javax.swing.JTextField();
        sil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        per_tel = new javax.swing.JTextField();
        cins = new javax.swing.JComboBox();
        geri = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        meslek_db = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        per_Tc = new javax.swing.JTextField();
        per_sicil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(242, 255, 232));

        jLabel7.setText("Personel Soyadı:");

        jLabel8.setText("Medeni Hali:");

        med_hal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz", "Evli", "Bekar", "Dul", " " }));

        jLabel9.setText("Brüt Maaş:");

        jLabel10.setText("Adres:");

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ŞUBE", "SİCİL NO", "ADI", "SOYADI", "CİNSİYET", "MEDENİ HAL", "TELEFON", "ADRES", "T.C NO", "MAAŞ", "MESLEK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo.setEnabled(false);
        jScrollPane1.setViewportView(tablo);
        if (tablo.getColumnModel().getColumnCount() > 0) {
            tablo.getColumnModel().getColumn(0).setResizable(false);
            tablo.getColumnModel().getColumn(1).setResizable(false);
            tablo.getColumnModel().getColumn(2).setResizable(false);
            tablo.getColumnModel().getColumn(3).setResizable(false);
            tablo.getColumnModel().getColumn(4).setResizable(false);
            tablo.getColumnModel().getColumn(5).setResizable(false);
            tablo.getColumnModel().getColumn(6).setResizable(false);
            tablo.getColumnModel().getColumn(7).setResizable(false);
            tablo.getColumnModel().getColumn(8).setResizable(false);
            tablo.getColumnModel().getColumn(9).setResizable(false);
            tablo.getColumnModel().getColumn(10).setResizable(false);
        }

        ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-save-close-64.png"))); // NOI18N
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        sube.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Şube Kodu" }));

        jLabel1.setText("Şube");

        ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-search-property-64.png"))); // NOI18N
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });

        guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-update-64.png"))); // NOI18N
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-delete-bin-64.png"))); // NOI18N
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        jLabel2.setText("Personel Adı");

        jLabel11.setText("Telefon:");

        jLabel3.setText("Cinsiyet");

        cins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz", "E", "K" }));

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-back-arrow-64.png"))); // NOI18N
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        jLabel4.setText("Meslek");

        meslek_db.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meslek Kodu" }));

        jLabel5.setText("T.C Kimlik Numarası");

        jLabel6.setText("Sicil Numarası:");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-name-tag-96.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ad_alani)
                                            .addComponent(per_sicil)
                                            .addComponent(per_Tc)
                                            .addComponent(soyad_alani)
                                            .addComponent(med_hal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cins, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(meslek_db, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sube, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adres_alani)
                                    .addComponent(per_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ekle)
                        .addGap(18, 18, 18)
                        .addComponent(ara)
                        .addGap(18, 18, 18)
                        .addComponent(sil)
                        .addGap(18, 18, 18)
                        .addComponent(guncelle)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(599, 599, 599))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(geri))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(per_Tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(per_sicil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(med_hal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(meslek_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adres_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(per_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ekle)
                            .addComponent(ara)
                            .addComponent(sil)
                            .addComponent(guncelle))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        // TODO add your handling code here:
        String ad= ad_alani.getText();
        String soyad= soyad_alani.getText();
        String sicilno= per_sicil.getText();
        String telefon = per_tel.getText();
        String maas= maas_alani.getText();
        String medenihal=(String) med_hal.getSelectedItem();
        String adres= adres_alani.getText();
        String tc =per_Tc.getText();
        String cinsiyet=(String) cins.getSelectedItem();
        String meslek= (String) meslek_db.getSelectedItem();
        String suube= (String)sube.getSelectedItem();
        
        String sorgu = "INSERT INTO PERSONEL(SUBE_ID,SICIL_NO,PERS_ADI,PERS_SOYADI,CINSIYET,MEDENI_HAL,TELEFON,ADRES,TC_NO,BRUT_MAAS,MESLEK_ID)" + "VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        if (tc.length()==11){
            try {
                pstmt=conn.prepareStatement(sorgu);
                pstmt.setString(1, suube);
                pstmt.setString(2, sicilno);
                pstmt.setString(3, ad);
                pstmt.setString(4, soyad);
                pstmt.setString(5, cinsiyet);
                pstmt.setString(6, medenihal);
                pstmt.setString(7, telefon);
                pstmt.setString(8,adres);
                pstmt.setString(9, tc);
                pstmt.setString(10, maas);
                pstmt.setString(11, meslek);
                pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Başarıyla Eklendi." ); 
            doldur();
        } catch (SQLException ex) {
            Logger.getLogger(Islemler.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
        else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
           ad_alani.setText("");
                        soyad_alani.setText("");
                        per_Tc.setText("");
                        per_sicil.setText("");
                        per_tel.setText("");
                        maas_alani.setText("");
                        adres_alani.setText("");                        
       }
        
        
    }//GEN-LAST:event_ekleActionPerformed

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
        // TODO add your handling code here:
         String tc =per_Tc.getText();
         String sorgu = "SELECT * FROM PERSONEL WHERE TC_NO = ?";
        if (tc.length()==11){
            try {
                pstmt=conn.prepareStatement(sorgu);
                //stmt =conn.createStatement();
                pstmt.setString(1, tc);
            
                ResultSet rs = pstmt.executeQuery();
                if(rs.next()== true ){
                    JOptionPane.showMessageDialog(null, "Kayıt Bulundu. ");
                    per_Tc.setText("");
                    //JOptionPane.showMessageDialog(null, "deneme");
                    System.out.print(rs.getString("SUBE_ID")+ " ");
                    System.out.print(rs.getString("SICIL_NO")+ " ");
                    System.out.print(rs.getString("PERS_ADI")+ " ");
                    System.out.print(rs.getString("PERS_SOYADI")+ " ");
                    System.out.print(rs.getString("CINSIYET")+ " ");
                    System.out.print(rs.getString("MEDENI_HAL")+ " ");                                      
                    System.out.print(rs.getString("TELEFON")+ " ");
                    System.out.print(rs.getString("ADRES")+ " ");
                    System.out.print(rs.getString("TC_NO")+ " ");
                    System.out.print(rs.getString("BRUT_MAAS")+ " ");
                    System.out.println("MESLEK_ID"+ " ");
                    
                }      //kayıtları tabloya yazdırmak gerek sadece
            
                else{
                    JOptionPane.showMessageDialog(null,"Kayıt Bulunamadı. " );
                    per_Tc.setText("");
                }
            
            } catch (SQLException ex) {
            Logger.getLogger(Islemler.class.getName()).log(Level.SEVERE, null, ex);
            
            }
        }
        else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
           ad_alani.setText("");
                        soyad_alani.setText("");
                        per_Tc.setText("");
                        per_sicil.setText("");
                        per_tel.setText("");
                        maas_alani.setText("");
                        adres_alani.setText("");                        
       }
        
    }//GEN-LAST:event_araActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        // TODO add your handling code here:
        String tc =per_Tc.getText();
         String sorgu = "DELETE * FROM PERSONEL WHERE TC_NO = ?";
        if (tc.length()==11){
            try {
                pstmt=conn.prepareStatement(sorgu);
                //stmt =conn.createStatement();
                pstmt.setString(1, tc);
            
                pstmt.executeQuery();
                JOptionPane.showMessageDialog(null, "Kayıt Silindi. ");
                per_Tc.setText("");
                doldur();
                    
            } catch (SQLException ex) {
                Logger.getLogger(Islemler.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Kayıt Silinemedi. " );
            
            }
        }
        else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
           per_Tc.setText("");
        }
        
    }//GEN-LAST:event_silActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        // TODO add your handling code here:
        String ad= ad_alani.getText();
        String soyad= soyad_alani.getText();
        String sicilno= per_sicil.getText();
        String telefon = per_tel.getText();
        String maas= maas_alani.getText();
        String medenihal=(String) med_hal.getSelectedItem();
        String adres= adres_alani.getText();
        String tc =per_Tc.getText();
        String cinsiyet=(String) cins.getSelectedItem();
        String meslek= (String) meslek_db.getSelectedItem();
        String suube= (String)sube.getSelectedItem();
        
        String sorgu = "UPDATE  PERSONEL  SET SUBE_ID = ? , SICIL_NO = ? ,PERS_ADI = ? ,PERS_SOYADI=?,CINSIYET = ? ,MEDENI_HAL = ?, TELEFON = ? , ADRES =? TC_NO = ?,BRUT_MAAS =?, MESLEK_ID =? WHERE TC_NO = ?";
        if (tc.length()==11){    
            try {
                pstmt=conn.prepareStatement(sorgu);
                pstmt.setString(1, suube);
                pstmt.setString(2, sicilno);
                pstmt.setString(3, ad);
                pstmt.setString(4, soyad);
                pstmt.setString(5, cinsiyet);
                pstmt.setString(6, medenihal);
                pstmt.setString(7, telefon);
                pstmt.setString(8,adres);
                pstmt.setString(9, tc);
                pstmt.setString(10, maas);
                pstmt.setString(11, meslek);
                pstmt.setString(12, tc);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Başarıyla Güncellendi." ); 
                doldur();
            } catch (SQLException ex) {
            Logger.getLogger(Islemler.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Kayıt Güncellenemedi. ");
             
            }
        }
        
        else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
           per_Tc.setText("");
           ad_alani.setText("");
                        soyad_alani.setText("");
                        per_Tc.setText("");
                        per_sicil.setText("");
                        per_tel.setText("");
                        maas_alani.setText("");
                        adres_alani.setText("");                        
       }
        
        
        
        
    }//GEN-LAST:event_guncelleActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        // TODO add your handling code here:

        Menu form = new Menu();
        form.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField adres_alani;
    private javax.swing.JButton ara;
    private javax.swing.JComboBox cins;
    private javax.swing.JButton ekle;
    private javax.swing.JButton geri;
    private javax.swing.JButton guncelle;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maas_alani;
    private javax.swing.JComboBox med_hal;
    private javax.swing.JComboBox meslek_db;
    private javax.swing.JTextField per_Tc;
    private javax.swing.JTextField per_sicil;
    private javax.swing.JTextField per_tel;
    private javax.swing.JButton sil;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JComboBox sube;
    private javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables
}