/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dersane;

import dersane.Connection.Islemler;
import dersane.Connection.Ogrenciler;
import dersane.Connection.OracleDbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukriye
 */
public class VeliBilgi extends javax.swing.JFrame {
     //Islemler islem =new Islemler();
    private  Connection conn =null;
    private Statement stmt = null;
    private PreparedStatement pstmt =null;
  
    /**
     * Creates new form VeliBilgi
     * 
     */
   public VeliBilgi(){
       initComponents();
       
       try {
            Class.forName(OracleDbConnection.driverName);
            try {
            conn =DriverManager.getConnection(OracleDbConnection.URL,OracleDbConnection.userName,OracleDbConnection.password);
            stmt=conn.createStatement();
            
            System.out.println("Bağlantı Başarılı ");
            } 
            catch (SQLException ex) {
                 System.out.println("Bağlantı Başarısız ");
                 System.out.println(ex);
            }
        } 
        catch (ClassNotFoundException ex) {
          System.out.println("Driver Bulunamadı ");
          System.out.println(ex);
        }
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kaydet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        tc_alani = new javax.swing.JTextField();
        veli_tc = new javax.swing.JTextField();
        veli_Ad = new javax.swing.JTextField();
        veli_Soyad = new javax.swing.JTextField();
        veli_Telefon = new javax.swing.JTextField();
        ara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(242, 255, 232));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-family-64.png"))); // NOI18N

        jLabel4.setText("Öğrenci T.C No:");

        jLabel7.setText("Veli T.C No:");

        jLabel1.setText("Veli Adı:");

        jLabel2.setText("Veli soyadı:");

        jLabel3.setText("Veli telefonu");

        kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-save-close-64.png"))); // NOI18N
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-back-arrow-64.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-update-64.png"))); // NOI18N
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-delete-bin-64.png"))); // NOI18N
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        tc_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc_alaniActionPerformed(evt);
            }
        });

        veli_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veli_tcActionPerformed(evt);
            }
        });

        veli_Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veli_AdActionPerformed(evt);
            }
        });

        veli_Soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veli_SoyadActionPerformed(evt);
            }
        });

        ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dersane/icons8-search-property-64.png"))); // NOI18N
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(veli_Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel2))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tc_alani, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(veli_tc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(veli_Ad)
                                    .addComponent(veli_Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)
                        .addComponent(ara))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(kaydet)
                        .addGap(26, 26, 26)
                        .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(veli_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(veli_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(veli_Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(ara)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(veli_Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guncelle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kaydet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sil, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void veli_AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veli_AdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veli_AdActionPerformed

    private void veli_SoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veli_SoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veli_SoyadActionPerformed

    private void veli_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veli_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veli_tcActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        // TODO add your handling code here:
        String tc= veli_tc.getText();
        String ad= veli_Ad.getText();
        String soyad =veli_Soyad.getText();
        String telefon = veli_Telefon.getText();
        String ogrtc=tc_alani.getText();
        
         if (tc.length()==11){

                    try {
                        String sorgu = "INSERT INTO VELI(VELI_TC,VELI_AD,VELI_SOYAD,VELI_TEL,OGRENCI_TC)" + "VALUES (?,?,?,?,?)";
                        pstmt=conn.prepareStatement(sorgu);
                        pstmt.setString(1, tc);
                        pstmt.setString(2, ad);
                        pstmt.setString(3, soyad);
                        pstmt.setString(4, telefon);
                        pstmt.setString(5, ogrtc);
                        pstmt.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Başarıyla Eklendi." );
                        tc_alani.setText("");
                        veli_Ad.setText("");
                        veli_Soyad.setText("");
                        veli_Telefon.setText("");
                        veli_tc.setText("");
                    } catch (SQLException ex) {
                        Logger.getLogger(VeliBilgi.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
           
        else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
           tc_alani.setText("");
                        veli_Ad.setText("");
                        veli_Soyad.setText("");
                        veli_Telefon.setText("");
                        veli_tc.setText("");
                        tc_alani.setText("");
       }   
    }//GEN-LAST:event_kaydetActionPerformed

    private void tc_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc_alaniActionPerformed

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
        // TODO add your handling code here:
        
        
         String tc= tc_alani.getText();
        if (tc.length()==11){
           //islemler.ogrenci_Ara(tc);
            String sorgu = "SELECT * FROM VELI WHERE OGRENCI_TC = ?";
        
        try {
            pstmt=conn.prepareStatement(sorgu);
            //stmt =conn.createStatement();
            pstmt.setString(1, tc);
            
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()== true ){
                JOptionPane.showMessageDialog(null, "Kayıt Bulundu. ");
                
                    //JOptionPane.showMessageDialog(null, "deneme");
                   /* System.out.print(rs.getString("SUBE_ID")+ " ");
                    System.out.print(rs.getString("TC_NO")+ " ");
                    System.out.print(rs.getString("OGR_ADI")+ " ");
                    System.out.print(rs.getString("OGR_SOYADI")+ " ");
                    System.out.print(rs.getString("CINSIYET")+ " ");
                    System.out.print(rs.getString("TELEFON")+ " ");
                    System.out.print(rs.getString("ADRES")+ " ");
                    tc_alani.setText("");*/
                /*
                System.out.print(rs.getString("VELI_TC")+ " ");
                    System.out.print(rs.getString("VELI_AD")+ " ");
                    System.out.print(rs.getString("VELI_SOYAD")+ " ");
                    System.out.print(rs.getString("VELI_TEL")+ " ");
                    System.out.print(rs.getString("OGRENCI_TC")+ " ");
                    */
               veli_Ad.setText(rs.getString("VELI_AD"));
               veli_Soyad.setText(rs.getString("VELI_SOYAD"));
               veli_Telefon.setText(rs.getString("VELI_TEL"));
               
                  
            }      //kayıtları tabloya yazdırmak gerek sadece
            
            else{
                JOptionPane.showMessageDialog(null,"Kayıt Bulunamadı. " );
                tc_alani.setText("");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Islemler.class.getName()).log(Level.SEVERE, null, ex);
            
        }
           
       }
       else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
       }
        
    }//GEN-LAST:event_araActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        // TODO add your handling code here:
        
        String tc= veli_tc.getText();
        String ad= veli_Ad.getText();
        String soyad =veli_Soyad.getText();
        String telefon = veli_Telefon.getText();
        String ogrtc=tc_alani.getText();
        
         if (tc.length()==11){
             //VELI_TC,VELI_AD,VELI_SOYAD,VELI_TEL,OGRENCI_TC
           String sorgu = "UPDATE  VELI  SET VELI_TC = ? , VELI_AD = ? ,VELİ_SOYAD = ? , VELI_TEL = ? , OGRENCI_TC =?   WHERE OGRENCI_TC = ?";
            try {
                pstmt=conn.prepareStatement(sorgu);
                 pstmt.setString(1, tc);
                        pstmt.setString(2, ad);
                        pstmt.setString(3, soyad);
                        pstmt.setString(4, telefon);
                        pstmt.setString(5, ogrtc);
                        pstmt.setString(6, ogrtc);
                         pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Kayıt Güncellendi. ");
            tc_alani.setText("");
                        veli_Ad.setText("");
                        veli_Soyad.setText("");
                        veli_Telefon.setText("");
                        veli_tc.setText("");
            
            } catch (SQLException ex) {
                Logger.getLogger(VeliBilgi.class.getName()).log(Level.SEVERE, null, ex);
            }
                       
         
         }
         else if (tc.length()>11 || tc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
           veli_Ad.setText("");
                        veli_Soyad.setText("");
                        veli_Telefon.setText("");
                        veli_tc.setText("");
       }
         
    }//GEN-LAST:event_guncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        // TODO add your handling code here:
        
        String ogrtc=tc_alani.getText();
        
        
        if (ogrtc.length()==11){
           //islemler.ogrenci_Sil(tc);
            String sorgu = "DELETE FROM VELI WHERE OGR_TC= ?";
        
        try {
            pstmt=conn.prepareStatement(sorgu);
           
            pstmt.setString(1, ogrtc);
            
           pstmt.executeQuery();
            
            JOptionPane.showMessageDialog(null, "Kayıt Silindi. ");
            tc_alani.setText("");
                        veli_Ad.setText("");
                        veli_Soyad.setText("");
                        veli_Telefon.setText("");
                        veli_tc.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Islemler.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Kayıt Silinemedi. " );
            
        }
           
       }
       else if (ogrtc.length()>11 || ogrtc.length()<11){
           JOptionPane.showMessageDialog(null, "T.C Kimlik Numarası 11 Haneli Olmalıdır.");
            tc_alani.setText("");
                        veli_Ad.setText("");
                        veli_Soyad.setText("");
                        veli_Telefon.setText("");
                        veli_tc.setText("");
       }
        
                        
    }//GEN-LAST:event_silActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu form = new Menu();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeliBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeliBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeliBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeliBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeliBilgi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ara;
    private javax.swing.JButton guncelle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kaydet;
    private javax.swing.JButton sil;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JTextField veli_Ad;
    private javax.swing.JTextField veli_Soyad;
    private javax.swing.JTextField veli_Telefon;
    private javax.swing.JTextField veli_tc;
    // End of variables declaration//GEN-END:variables
}
